// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSnQ74yBb-lYPFrjvhf_m9xKoqT670DMw',
    appId: '1:1004379594579:web:9c9ce66a86705d40c08ba6',
    messagingSenderId: '1004379594579',
    projectId: 'cov-app-71e00',
    authDomain: 'cov-app-71e00.firebaseapp.com',
    storageBucket: 'cov-app-71e00.firebasestorage.app',
    measurementId: 'G-T2K1LRB6F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACdumZYQ6F_rnrpfpP7pwSDO3oK8ihuh4',
    appId: '1:1004379594579:android:7048fc3af6abffa6c08ba6',
    messagingSenderId: '1004379594579',
    projectId: 'cov-app-71e00',
    storageBucket: 'cov-app-71e00.firebasestorage.app',
  );
}
